# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/strange-theme-417619
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.4-ba474a0"
  os: linux
  arch: amd64

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
